### ISSUE TITLE
Fix installation/deployment issues in the README

### ISSUE THREAD

**Issue by dnpotter** [Bubble-Protocol/trivial-bubble-server#5]
Subtask of #3

Update the readme if there are any mistakes in the installation instructions or missing steps.  Are the configuration instructions sufficient?  Are the testing instructions sufficient?

**Comment by onirudda-islam** [comment]
### Related Issues
- Closes #5 (Updated the README for installation, configuration, and testing instructions)

### Summary of Changes
- Enhanced configuration instructions to ensure clarity and completeness.
- Improved testing instructions to provide clear steps for running the test suite.

### Checklist
- [x] I have tested the changes locally.
- [x] I have updated the documentation (README).

### Additional Comments
- The README is now more user-friendly and should help new users set up and test the server without confusion. Please review the changes and provide feedback.
